In [116]:
import pandas as pd
import numpy as np
import os
data_dir = '/datadrive/satyendra.pandey/sessions/kaggle/data'

In [117]:
dateparse = lambda dates: pd.datetime.strftime(pd.datetime.strptime(dates, '%Y-%m-%d %H:%M:%S'),"%a")
event_df= pd.read_csv(os.path.join(data_dir,'events.csv'), dtype = {'device_id': np.str},
                      date_parser=dateparse,parse_dates=['timestamp'] )

In [135]:
del event_df['event_id']
df1 = event_df.ix[(event_df.longitude!=0.00) | (event_df.latitude!=0.00),
                  ['device_id','timestamp','longitude','latitude']]

In [136]:
df1['loc'] = df1.longitude.astype('str') + '-' + df1.latitude.astype('str')
del df1['longitude']
del df1['latitude']

In [138]:
df1.drop_duplicates(['device_id','loc','timestamp'],inplace=True)

In [139]:
df1.groupby(['device_id','timestamp']).count().reset_index(inplace=True)

In [142]:
df1.ix[:,'loc'] = 1
event_day_loc_cnt = pd.pivot_table(df1,values='loc', columns='timestamp', 
                                   index='device_id', aggfunc=np.sum).reset_index()

In [179]:
df2 = event_df.ix[(event_df.longitude==0.00) & (event_df.latitude==0.00)]
df2 = df2.groupby(['device_id']).count().reset_index()
del df2['latitude']
del df2['longitude']
df2.rename(columns={'timestamp':'unknow_loc_cnt'}, inplace=True)
event_day_loc = pd.merge(event_day_loc_cnt,df2, how='outer', on='device_id').fillna(0)

In [178]:
event_day_loc

timestamp,device_id,Fri,Mon,Sat,Sun,Thu,Tue,Wed,unknow_loc_cnt
0,-1000667340060427374,8,1,1,1,3,2,5,78
1,-100098646088222553,0,0,0,0,0,0,1,0
2,-100101996136889832,0,0,1,0,0,0,0,0
3,-1001337759327042486,4,0,13,0,0,2,5,0
4,-1002343061859436033,1,1,13,1,3,3,6,0
5,-1002733576670974332,0,0,0,1,0,0,0,50
6,-1003115270132638814,4,7,9,2,4,3,2,33
7,-1003656692718752939,0,1,2,1,2,1,2,1
8,-1004894663131317639,1,1,1,1,1,1,1,51
9,-1005325275801475257,1,0,1,0,0,0,0,3
10,-1005337197395399686,0,1,1,1,1,0,1,2
11,-1005411102947247412,1,0,0,0,1,0,0,12
12,-1006304051333156281,0,1,0,0,0,0,0,0
13,-1006357788560227421,0,1,1,0,1,0,0,1
14,-1006787244607321743,1,0,1,0,1,0,0,11
15,-1007805635694865738,0,1,0,1,1,3,0,3
16,-1008172259872900192,0,0,1,0,0,0,0,0
17,-1009243782481385445,0,1,0,0,1,0,1,13
18,-1009422368604632077,0,0,1,0,0,0,0,0
19,-1010331399860272993,0,0,0,1,0,0,0,0
20,-1010629213487766981,2,1,3,1,2,2,2,17
21,-1010684607686279821,3,1,2,1,2,3,2,3
22,-1010835662119618572,0,1,3,0,1,0,2,0
23,-1011538057032334587,0,0,1,0,0,0,0,3
24,-1014824673180372612,1,1,1,0,0,2,0,10
25,-101526631695223557,0,1,0,0,0,1,1,1
26,-1015549920007440518,0,1,0,1,0,0,0,0
27,-1016262857591722557,1,1,1,1,0,0,1,21
28,-1016349108712647621,0,0,0,0,0,0,1,6
29,-1016613970221052120,0,1,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...
60835,985343554649646987,0,0,0,0,0,0,0,54
60836,985357795198410741,0,0,0,0,0,0,0,4
60837,985983550146131347,0,0,0,0,0,0,0,1
60838,986402657516349410,0,0,0,0,0,0,0,1
60839,986633134223526075,0,0,0,0,0,0,0,131
60840,987071853830697622,0,0,0,0,0,0,0,17
60841,987341152959347971,0,0,0,0,0,0,0,4
60842,987731093733347791,0,0,0,0,0,0,0,26
60843,988322422143841285,0,0,0,0,0,0,0,15
60844,98858280551155742,0,0,0,0,0,0,0,8
60845,988700349486667753,0,0,0,0,0,0,0,8
60846,989828853240061660,0,0,0,0,0,0,0,17
60847,989868889130036553,0,0,0,0,0,0,0,14
60848,990474436636925779,0,0,0,0,0,0,0,12
60849,991915315555169207,0,0,0,0,0,0,0,1
60850,992232612925573959,0,0,0,0,0,0,0,4
60851,993894748934539938,0,0,0,0,0,0,0,2
60852,994064354010417334,0,0,0,0,0,0,0,11
60853,99479029389286800,0,0,0,0,0,0,0,73
60854,994957985493748350,0,0,0,0,0,0,0,26
60855,995105732491005377,0,0,0,0,0,0,0,9
60856,995603547873292795,0,0,0,0,0,0,0,17
60857,996058133418507594,0,0,0,0,0,0,0,32
60858,996093048442249826,0,0,0,0,0,0,0,2
60859,996163203858940369,0,0,0,0,0,0,0,1
60860,996189249308913147,0,0,0,0,0,0,0,7
60861,996542697367587052,0,0,0,0,0,0,0,10
60862,997114351076526160,0,0,0,0,0,0,0,2
60863,997893466461332786,0,0,0,0,0,0,0,7
60864,99976251796408156,0,0,0,0,0,0,0,3